FROM python:3.6.1-alpine
MAINTAINER Edward Leoni

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_KEY_ID
ARG AWS_REGION_NAME
ARG LEX_BOT_NAME
ARG LEX_BOT_ALIAS
ARG LEX_USER_ID

ENV FLASK_APP = "/app/app.py"
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_KEY_ID=$AWS_SECRET_KEY_ID
ENV AWS_REGION_NAME=$AWS_REGION_NAME
ENV LEX_BOT_NAME=$LEX_BOT_NAME
ENV LEX_BOT_ALIAS=$LEX_BOT_ALIAS
ENV LEX_USER_ID=$LEX_USER_ID

RUN mkdir /app
WORKDIR /app

ADD . .

RUN echo "python /app/app.py -m flask run" > /run.sh

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["sh", "/run.sh"]
